<html>
<head>
<title>TestNG:  Test</title>
<link href="../testng.css" rel="stylesheet" type="text/css" />
<link href="../my-testng.css" rel="stylesheet" type="text/css" />

<style type="text/css">
.log { display: none;} 
.stack-trace { display: none;} 
</style>
<script type="text/javascript">
<!--
function flip(e) {
  current = e.style.display;
  if (current == 'block') {
    e.style.display = 'none';
    return 0;
  }
  else {
    e.style.display = 'block';
    return 1;
  }
}

function toggleBox(szDivId, elem, msg1, msg2)
{
  var res = -1;  if (document.getElementById) {
    res = flip(document.getElementById(szDivId));
  }
  else if (document.all) {
    // this is the way old msie versions work
    res = flip(document.all[szDivId]);
  }
  if(elem) {
    if(res == 0) elem.innerHTML = msg1; else elem.innerHTML = msg2;
  }

}

function toggleAllBoxes() {
  if (document.getElementsByTagName) {
    d = document.getElementsByTagName('div');
    for (i = 0; i < d.length; i++) {
      if (d[i].className == 'log') {
        flip(d[i]);
      }
    }
  }
}

// -->
</script>

</head>
<body>
<h2 align='center'>Test</h2><table border='1' align="center">
<tr>
<td>Tests passed/Failed/Skipped:</td><td>7/2/0</td>
</tr><tr>
<td>Started on:</td><td>Sun Apr 03 11:32:04 ICT 2022</td>
</tr>
<tr><td>Total time:</td><td>29 seconds (29511 ms)</td>
</tr><tr>
<td>Included groups:</td><td></td>
</tr><tr>
<td>Excluded groups:</td><td></td>
</tr>
</table><p/>
<small><i>(Hover the method name to see the test class name)</i></small><p/>
<table width='100%' border='1' class='invocation-failed'>
<tr><td colspan='4' align='center'><b>FAILED TESTS</b></td></tr>
<tr><td><b>Test method</b></td>
<td width="30%"><b>Exception</b></td>
<td width="10%"><b>Time (seconds)</b></td>
<td><b>Instance</b></td>
</tr>
<tr>
<td title='qaautomation.march2022.AppTestAfterPOM.loginInvalidPassword()'><b>loginInvalidPassword</b><br>Test class: qaautomation.march2022.AppTestAfterPOM</td>
<td><div><pre>java.lang.AssertionError: expected [true] but found [false]
	at qaautomation.march2022.AppTestAfterPOM.loginInvalidPassword(AppTestAfterPOM.java:59)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 14 stack frames</pre></div><a href='#' onClick='toggleBox("stack-trace1809694448", this, "Click to show all stack frames", "Click to hide stack frames")'>Click to show all stack frames</a>
<div class='stack-trace' id='stack-trace1809694448'><pre>java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:96)
	at org.testng.Assert.failNotEquals(Assert.java:776)
	at org.testng.Assert.assertTrue(Assert.java:44)
	at org.testng.Assert.assertTrue(Assert.java:54)
	at qaautomation.march2022.AppTestAfterPOM.loginInvalidPassword(AppTestAfterPOM.java:59)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
</pre></div></td>
<td>0</td>
<td>qaautomation.march2022.AppTestAfterPOM@67080771</td></tr>
<tr>
<td title='qaautomation.march2022.AppTestAfterPageFactory.loginInvalidPassword()'><b>loginInvalidPassword</b><br>Test class: qaautomation.march2022.AppTestAfterPageFactory</td>
<td><div><pre>java.lang.AssertionError: expected [true] but found [false]
	at qaautomation.march2022.AppTestAfterPageFactory.loginInvalidPassword(AppTestAfterPageFactory.java:59)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 14 stack frames</pre></div><a href='#' onClick='toggleBox("stack-trace1588742100", this, "Click to show all stack frames", "Click to hide stack frames")'>Click to show all stack frames</a>
<div class='stack-trace' id='stack-trace1588742100'><pre>java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:96)
	at org.testng.Assert.failNotEquals(Assert.java:776)
	at org.testng.Assert.assertTrue(Assert.java:44)
	at org.testng.Assert.assertTrue(Assert.java:54)
	at qaautomation.march2022.AppTestAfterPageFactory.loginInvalidPassword(AppTestAfterPageFactory.java:59)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
</pre></div></td>
<td>0</td>
<td>qaautomation.march2022.AppTestAfterPageFactory@72cde7cc</td></tr>
</table><p>
<table width='100%' border='1' class='invocation-passed'>
<tr><td colspan='4' align='center'><b>PASSED TESTS</b></td></tr>
<tr><td><b>Test method</b></td>
<td width="30%"><b>Exception</b></td>
<td width="10%"><b>Time (seconds)</b></td>
<td><b>Instance</b></td>
</tr>
<tr>
<td title='qaautomation.march2022.AppTestAfterPOM.loginSuccess()'><b>loginSuccess</b><br>Test class: qaautomation.march2022.AppTestAfterPOM</td>
<td></td>
<td>0</td>
<td>qaautomation.march2022.AppTestAfterPOM@67080771</td></tr>
<tr>
<td title='qaautomation.march2022.AppTestAfterPageFactory.loginSuccess()'><b>loginSuccess</b><br>Test class: qaautomation.march2022.AppTestAfterPageFactory</td>
<td></td>
<td>0</td>
<td>qaautomation.march2022.AppTestAfterPageFactory@72cde7cc</td></tr>
<tr>
<td title='qaautomation.march2022.AppTestAfterPOM.loginWithoutSubmitLoginBtn()'><b>loginWithoutSubmitLoginBtn</b><br>Test class: qaautomation.march2022.AppTestAfterPOM</td>
<td></td>
<td>0</td>
<td>qaautomation.march2022.AppTestAfterPOM@67080771</td></tr>
<tr>
<td title='qaautomation.march2022.AppTestAfterPageFactory.loginWithoutSubmitLoginBtn()'><b>loginWithoutSubmitLoginBtn</b><br>Test class: qaautomation.march2022.AppTestAfterPageFactory</td>
<td></td>
<td>0</td>
<td>qaautomation.march2022.AppTestAfterPageFactory@72cde7cc</td></tr>
<tr>
<td title='qaautomation.march2022.AppTestAfterRefactor.test()'><b>test</b><br>Test class: qaautomation.march2022.AppTestAfterRefactor</td>
<td></td>
<td>0</td>
<td>qaautomation.march2022.AppTestAfterRefactor@1eb5174b</td></tr>
<tr>
<td title='qaautomation.march2022.AppTestAfterRefactor.test2()'><b>test2</b><br>Test class: qaautomation.march2022.AppTestAfterRefactor</td>
<td></td>
<td>0</td>
<td>qaautomation.march2022.AppTestAfterRefactor@1eb5174b</td></tr>
<tr>
<td title='qaautomation.march2022.AppTestAfterRefactor.test3()'><b>test3</b><br>Test class: qaautomation.march2022.AppTestAfterRefactor</td>
<td></td>
<td>0</td>
<td>qaautomation.march2022.AppTestAfterRefactor@1eb5174b</td></tr>
</table><p>
</body>
</html>